import { Router } from 'express';
import { validate } from '../../middlewares/validate.js';
import { authenticate } from '../../middlewares/auth.js';
import { credentialsSchema, loginSchema, logoutSchema, refreshSchema } from './auth.schema.js';
import * as c from './auth.controller.js';
export const authRouter = Router();
authRouter.post('/register', validate({ body: credentialsSchema }), c.register);
authRouter.post('/login', validate({ body: loginSchema }), c.login);
authRouter.post('/refresh', validate({ body: refreshSchema }), c.refresh);
authRouter.post('/logout', authenticate, validate({ body: logoutSchema }), c.logout);
authRouter.get('/me', authenticate, c.me);
